import React from 'react';

export default function Contract(props) {

	return (
		<div className="contract">
			<h3><strong>RELEASE AND WAIVER OF LIABILITY, ASSUMPTION OF RISK, AND INDEMNITY AGREEMENT</strong></h3>
			<p><strong>1. 	I HEREBY GENERALLY AND SPECIFICALLY RELEASE, WAIVE, DISCHARGE, AND COVENANT NOT TO SUE</strong> Baseball and Softball, Inc. or any of its affiliates, directors, officers, members, shareholders, employees, representatives, contractors, agents, officials, committee members, teams, managers, coaches, players, participants, facility owners and lessees, sponsors, advertisers, donors, volunteers, guests, invitees, predecessors and successors in interest, assigns, and all persons assisting in the conduct of Baseball and Softball, Inc. activities or events  Baseball and Softball, Inc. and the foregoing persons, individuals, entities, and third parties shall each hereinafter be referred to as a “RELEASEE” or collectively the “RELEASEES”), FROM ANY AND ALL PAST, PRESENT OR FUTURE CLAIMS, DEMANDS, LIABILITIES, ACTIONS, CAUSES OF ACTION, SUITS, JUDGMENTS, ORDERS, HEARINGS, PROCEEDINGS, LOSSES, DAMAGES, COSTS, EXPENSES, OBLIGATIONS, INCLUDING, WITHOUT LIMITATION, ATTORNEYS’ FEES AND ANY AND ALL FEES OR COSTS OF EVERY NATURE, CHARACTER OR DESCRIPTION WHATSOEVER (the foregoing shall each hereinafter be referred to as a “Claim” or collectively as the “Claims”), ARISING OUT OF, RELATED TO, IN CONNECTION WITH, OR ON ACCOUNT OF ANY BASEBALL AND SOFTBALL, INC. EVENT OR OTHER ACTIVITY, including, without limitation, any Claim involving personal injury (including death) or property damage; and from any cause whatsoever, including, without limitation, the failure of anyone to enforce rules and regulations, to make inspections, the condition of any portion of the field, facilities, or premises, defective products, any act or omission of the RELEASEES, or any other act WHETHER CAUSED BY THE NEGLIGENCE OF THE RELEASEES OR OTHERWISE. This release, waiver, discharge, and covenant not to sue also expressly covers all Claims arising from or in any way related to my presence, attendance, or participation, or the presence, attendance, or participation of my child, for any reason whatsoever at the facilities of or used by Baseball and Softball, Inc. or any Releasee, or on the premises where Baseball and Softball, Inc. events and/or activities take place, including, without limitation, my involvement as a spectator, or my child’s involvement as a player or participant, and such release and waiver is extended to include all transportation to and from all activities and events. This release, waiver, discharge, and covenant not to sue also expressly covers all Claims against any RELEASEE for personal injuries (including death) or property damage sustained as a result of NEGLIGENT RESCUE OPERATIONS OR PROCEDURES.</p>
				<p><strong>
				2. 	I HEREBY AGREE TO INDEMNIFY AND SAVE AND HOLD HARMLESS THE RELEASEES</strong> and each of them from any and all Claims they or any of them may incur or sustain arising from, related to, in connection with, or on account of any injury to or death of any person or damage to property, caused or alleged to be caused in whole or in part by the negligence of RELEASEES or otherwise, arising from or related in any way to any Baseball. event or activity.  If despite the release set forth herein, I, my child, or anyone acting on my behalf or on behalf of my child, makes a Claim against any of the RELEASEES, I agree to indemnify, save and hold harmless, and defend, at my sole cost and expense, the RELEASEES, and each of them, from any and all such Claims that may be brought or instituted against the RELEASEES, whether the Claim is based on the negligence of the RELEASEES or otherwise arising from or related in any way to any Baseball. event or activity.  My obligation to indemnify shall survive my participation and my child’s participation in Baseball. events or activities for the full period of time allowed by law.  I further agree to pay and satisfy any judgment, award or decree that may be rendered against Baseball. or any RELEASEE in connection with my participation or my child’s participation in Baseball. events or activities.  I further agree to reimburse Baseball. and any RELEASEE any and all legal expenses and costs incurred by each of them in connection therewith or in enforcing the indemnity herein provided.</p>
			</div>
	);
}